### ISSUE TITLE
please take a look on name example

### ISSUE THREAD

**Issue by tallinn-learning** [VeronikaOstrovski/homework03#1]
https://github.com/VeronikaOstrovski/homework03/blob/d010b944762c9c7cda4a6fe5b86593ea42e0d0ef/src/Age.java#L1

int johnsAge = 25;
int marysAge = 18;

boolean isJohnOlder = johnsAge > marysAge;
boolean areTheySameAge = johnsAge == marysAge;

**Comment by VeronikaOstrovski** [comment]
Поняла, что надо давать более точные названия. Спасибо. Исправила
И для boolean при написании метода имя метода начинается с is или are?

**Comment by tallinn-learning** [comment]
is обычно
