### ISSUE TITLE
names of variable

### ISSUE THREAD

**Issue by tallinn-learning** [VeronikaOstrovski/homework03#2]
https://github.com/VeronikaOstrovski/homework03/blob/d010b944762c9c7cda4a6fe5b86593ea42e0d0ef/src/DoubleInt.java#LL6C9-L7C25

double floatingNumber = 3.5;
int integerNumber = (int) floatingNumber;

**Comment by VeronikaOstrovski** [comment]
Здесь не совсем понимаю, почему название у переменной такое?

**Comment by tallinn-learning** [comment]
на уроке давайте обсудим
